[package]
name = "wei-server"
version = "0.1.3"
edition = "2021"
description = "wei api"
documentation = "https://github.com/zuiyue-com/wei-server"
homepage = "https://github.com/zuiyue-com/wei-server"
license = "MIT OR Apache-2.0"

[dependencies]
wei-env = "0.2.13"
wei-run = "0.3.1"
wei-log = "0.2.10"
wei-single = "0.3.6"
wei-windows = { path = "../wei-windows"}

serde = "1"
serde_json = "1"
axum = "0.6.20"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.4.4", features = ["full"] } #"cors", "fs", "add_extension"
hyper = "0.14.27"
hyper-tls = "0.5.0"
flate2 = "1.0.28"
async-process = "1.8.1"
once_cell = "1.18.0"
sled = "0.34.7"

[target.'cfg(target_os = "linux")'.dependencies.openssl-sys]
version = "0.9"
features = ["vendored"]

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
winapi = { version = "0.3", features = ["winbase"] }
